services:
  - type: web
    name: url-shortener-frontend
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    initialDeployHook: sleep 60
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://url-shortener-frontend-f9ew.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://shrinkr-2k0u.onrender.com
      - key: DATABASE_URL
        sync: false # This will be set manually in Render dashboard
      - key: NEXTAUTH_SECRET
        generateValue: true # This will generate a random value
      - key: GOOGLE_CLIENT_ID
        sync: false # Set this manually in Render dashboard
      - key: GOOGLE_CLIENT_SECRET
        sync: false # Set this manually in Render dashboard
      - key: GITHUB_CLIENT_ID
        sync: false # Set this manually in Render dashboard
      - key: GITHUB_CLIENT_SECRET
        sync: false # Set this manually in Render dashboard 